---

- name: Install Apache and Upload my Web page
  hosts: STAGING_SERVERS
  become: yes

  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks:
  - name: Update apt-get repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install Apache Web Server
    apt: name=apache2 state=latest

  - name: Install MINI-HTTPD Web Server
    apt: name=mini-httpd state=latest

  - name: Copy myHomePage to Servers
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache

  - name: Start WebServer and make it enable on boot
    service: name=mini-httpd state=started enabled=yes

  handlers:
  - name: Restart Apache
    service: name=mini-httpd state=restarted

...